window.PROJECT_DATA = [
  {
    id: "sustain",
    name: "SUSTAIN",
    skills: [
      "Hackathon",
      "Python",
      "API Integration",
      "Natural Language Processing (NLP)",
      "Token Optimization",
      "Prompt Engineering",
      "Asynchronous Programming",
      "Model-View Separation",
      "Local Data Persistence",
      "Efficiency-Focused System Design",
      "Environmental Sustainability in Computing",
      "Command-Line Interface (CLI) Development",
      "GUI Development",
      "User Input Preprocessing",
      "Data Filtering Algorithms"
    ],
  },
  {
    id: "travelgo",
    name: "travelGo",
    skills: [
      "Software Design & Analysis",
      "Java",
      "JavaFX",
      "GUI Development",
      "Model-View Separation",
      "Local Data Persistence",
      "XML Data Handling",
      "XML Serialization",
      "CRUD Operations",
      "Filtering & Sorting Systems",
      "Dialog-Based Input Forms",
      "Input Validation",
      "User Authentication",
      "Maven",
      "Unit Testing",
      "Integration Testing",
      "System Testing",
      "JUnit",
      "Memory & Resource Management",
      "File I/O Validation",
      "Version Control: Git & GitHub"
    ],
  },
  {
    id: "lockin",
    name: "LockIn",
    skills: [
      "Software Systems, Development & Integration",
      "Java",
      "JavaFX",
      "GUI Development",
      "Client-Server Architecture",
      "Socket Programming",
      "Multi-Threading",
      "User Authentication",
      "Local Data Persistence",
      "Model-View Separation",
      "Collaborative Features",
      "Pomodoro Timer",
      "Whiteboard Collaboration",
      "Asynchronous Programming",
      "Version Control: Git & GitHub"
    ],
  },
  {
    id: "aircraft-analysis",
    name: "Analysis of Aircraft Fatalities",
    skills: [
      "Data Analysis",
      "Python",
      "Pandas",
      "Seaborn",
      "Matplotlib",
      "Data Cleaning",
      "Exploratory Data Analysis (EDA)",
      "Data Visualization",
      "Statistical Summaries",
      "Feature Grouping & Aggregation",
      "Kernel Density Estimation (KDE)",
      "Barplot & Countplot Visualization",
      "CSV Data Handling",
      "Insight Interpretation",
      "Version Control: Git & GitHub"
    ],
  },
  {
    id: "lester",
    name: "Lester",
    skills: [
      "Mobile App Development",
      "Flutter",
      "Dart",
      "GUI Development",
      "State Management",
      "Local Data Persistence",
      "SQLite (Local Storage)",
      "Model-View Separation",
      "Navigation & Screen Flow",
      "Asynchronous Programming",
      "Custom Theming",
      "Widget Tree Composition",
      "Form Handling & Validation",
      "User Journaling Features",
      "Mood Tracking",
      "Daily Challenge System",
      "Version Control: Git & GitHub"
    ],
  },
  {
    id: "rocket-type-tester",
    name: "Rocket Type Tester",
    skills: [
      "Python",
      "Pygame",
      "GUI Development",
      "Event-Driven Programming",
      "Real-Time Input Handling",
      "State Management",
      "Game Loop Architecture",
      "Performance & Frame Timing Control",
      "User Experience (UX) Design",
      "Menu & Screen Flow",
      "Asset Management (Images/Resources)",
      "Version Control: Git & GitHub"
    ],
  },
  {
    id: "battleship",
    name: "Battleship",
    skills: [
      "Java",
      "Object-Oriented Programming (OOP)",
      "2D Array Data Structures",
      "Game Logic Implementation",
      "User Input Handling",
      "Control Flow & Looping Constructs",
      "Modular Code Design",
      "Method Decomposition",
      "Command-Line Interface (CLI)",
      "Data Validation & Error Checking",
      "Turn-Based System Logic",
      "Version Control: Git & GitHub"
    ],
  },
  {
    id: "iris-mlp",
    name: "Iris Classification with MLP",
    skills: [
      "Machine Learning",
      "Python",
      "PyTorch",
      "Torchmetrics",
      "NumPy",
      "Matplotlib",
      "Supervised Learning",
      "Multilayer Perceptron (MLP)",
      "Classification Models",
      "Neural Network Training",
      "ReLU Activation",
      "Cross-Entropy Loss",
      "Adam Optimizer",
      "Model Evaluation",
      "Accuracy & Loss Visualization",
      "Feature Embedding Projection",
      "Data Preprocessing",
      "Dataloaders & Batching",
      "Version Control: Git & GitHub"
    ],
  },
  {
    id: "grade-entry-flutter-app",
    name: "Grade Entry Flutter App",
    skills: [
      "Mobile App Development",
      "Flutter",
      "Dart",
      "SQLite (Local Storage)",
      "Local Data Persistence",
      "Asynchronous Programming",
      "State Management",
      "Model-View Separation",
      "CRUD Operations",
      "Database Initialization & Querying",
      "Form Handling & Validation",
      "Widget Tree Composition",
      "Navigation & Screen Flow",
      "Error Handling",
      "User Input Validation",
      "Data Modeling",
      "Version Control: Git & GitHub"
    ],
  },
  {
    id: "functional-dependencies-bcnf",
    name: "Functional Dependencies & BCNF",
    skills: [
      "Database Systems & Concepts",
      "Python",
      "Relational Algebra Operations",
      "Functional Dependency Reasoning",
      "Attribute Closure Computation",
      "BCNF Decomposition",
      "Schema Normalization",
      "Data Validation & Error Checking",
      "Modular Code Design",
      "Version Control: Git & GitHub"
    ],
  },
  {
    id: "chinook-sql-analysis",
    name: "Chinook SQL Analysis",
    skills: [
      "SQL",
      "Relational Database Design",
      "Query Optimization",
      "Data Cleaning",
      "Feature Grouping & Aggregation",
      "Statistical Summaries",
      "Data Visualization",
      "CSV Data Handling",
      "Window Functions",
      "Common Table Expressions (CTEs)",
      "Exploratory Data Analysis (EDA)",
      "Insight Interpretation",
      "Version Control: Git & GitHub"
    ],
  },
];